# GitHub action to build software.
# Linux builds include pre-built dependencies via containers.

name: Build
on:
  pull_request:
  push:
    branches: [github-actions]

jobs:
  ubuntu_20_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-20.04:latest

    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: pwd
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
      - run: pwd
  
  ubuntu_18_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-18.04:latest

    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
  
  ubuntu_16_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-16.04:latest

    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
  
  centos_7_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-centos-7:latest

    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/centos_dist_pkgs
        shell: bash
